### ISSUE TITLE
Terminal Glasses not showing anything

### ISSUE THREAD

**Issue by deregges** [OpenMods/OpenPeripheral-Addons#44]
Since snapshot #144 the Terminal Glasses aren't showing anything.
The functions still return the right tables with the right values stored but it's not shown on the Glasses.
Checked .getUsers() - is connected.
I also had this bug with no mods installed.

*Rolled back to #143 until fixed*

**Comment by boq** [comment]
Well, have you read changelog for latest release? That bit about `.sync()`?

[Here's](https://github.com/OpenMods/OpenPeripheral-Addons/issues/43#issuecomment-68153558) background behind this decision.
