### ISSUE TITLE
The peripheral.getType of terminal glasses bridge returns openperipheral_ticketmachine

### ISSUE THREAD

**Issue by kla-sch** [OpenMods/OpenPeripheral-Addons#48]
I am using DW20 1.0.3 which claims to use 0.2.0-snapshot-139. The peripheral.getType(side) of terminal glasses bridge returns "openperipheral_ticketmachine" instead of "openperipheral_glassesbridge". It worked in DW20 1.0.2 (OPA 0.2.0-snapshot-122).

**Comment by boq** [comment]
Fixed in 76569d5213beaf7e83bc82d01ef63d308aae235a.

We released OpenPeripheralAddons-145 as official version month ago. Always check if you have recent version before reporting. Especially when it's DW20 pack.
