### ISSUE TITLE
Thaumcraft warp effect causes terminal glasses to go black until mc restart

### ISSUE THREAD

**Issue by michael-3-141** [OpenMods/OpenPeripheral-Addons#50]
I've been having this issue with the terminal glasses for a while now, but now I saw that when the screen goes dark on the sides because of thaumcraft warp, it for some reason makes the terminal glasses go completely black, but only if there are any boxes drawn on them. Any boxes that were drawn before and any new boxes drawn cause the whole screen to become black. I don't know on which side it is (thaumcraft or openperipherals) so I'm posting this on both, just in case.

**Comment by lights0123** [comment]
I've noticed this also. It also makes the screen completely dark if there are ANY boxes, liquids, fluids, or icons. There doesn't have to be any warp (I disabled that), Thaumcraft just has to be installed. I'm running:

p=peripheral.wrap("bottom")
p.addLiquid(2,2,10,10,"lava")
p.sync()

and before I uninstalled Thaumcraft, the screen turned completely pitch-black, except for my hotbar. However, text does not seem to do that. Also, I saw Azanor just deny that it was on his side. I hope this gets resolved.
