### ISSUE TITLE
Terminal Glasses not recognizing users or syncing

### ISSUE THREAD

**Issue by soupmeister** [OpenMods/OpenPeripheral-Addons#51]
I am able to wrap the bridge and call its methods just fine. I've also noticed that getUsers() returns a blank table, and chat commands don't work, so I know it's not a graphical glitch of being unable to render the overlay. I've double checked my glasses match the GUID of the bridge, and syncing does not help. Here's an example of the simple code I'm using:

t = peripheral.wrap("left")
t.addBox(1,1,10,10,0xFFFFFF,0.2)
t.sync()
t.getUsers()

I have created a new bridge, new glasses, and tried rebooting while wearing the glasses, along with destroying all involved blocks and starting from scratch. Thanks.

Running OpenPeripheralsCore 0.6.0, OpenPeripheralIntegration 0.1.0, and OpenPeripheralAddons 0.2.0 on a FluxGalaxy v0.7.16 server.

**Comment by boq** [comment]
Ok, I already got your report on OpenMods/OpenPeripheral#229. But thanks for correcting (and providing decent report with versions &lt;/rant&gt;)

Anyway, I probably don't have much to do here - I changed few parts of glasses since relase and fixed few bugs here and there - so I'm not sure this one is still valid.

**Comment by nevercast** [comment]
@soupmeister Is this still an issue? It is better that you check it as you've already the setup to do so.

**Comment by WolfieWaffle** [comment]
I think it is still an issue. I can't seem to get it to do anything no matter how many tutorials I watch and how many different things I try.

**Comment by nevercast** [comment]
These mod versions are significantly old!

I'm going to close this issue on the basis that it's for a very old collection of OP. Please create a new issue in the appropriate repository for any other problems you may encounter after updating.
