### ISSUE TITLE
Please add ComputerCraft 1.7 Support

### ISSUE THREAD

**Issue by KamranMackey** [OpenMods/OpenPeripheral-Addons#53]
I was wondering if you guys could please add ComputerCraft 1.7 support, because I can't load Minecraft with ComputerCraft 1.7 & OpenPeripheral-Addons installed. Says that it requires 1.64 & not any newer versions, or apparently OPA is just not noticing ComputerCraft at all. So could you guys please add ComputerCraft 1.7 detection to OPA so that I don't keep getting an error saying that I need CC 1.64? Thanks.

Here's the log: https://paste.ee/p/9D0Ba

**Comment by excelcrafter** [comment]
yeah, it doesnt work with computercraft 1.72

**Comment by boq** [comment]
All that was needed was some patience. Everything works with CC 1.73

**Comment by excelcrafter** [comment]
sorry for impatience :-D
