### ISSUE TITLE
Same version, different mod...?

### ISSUE THREAD

**Issue by jilleJr** [OpenMods/OpenPeripheral-Addons#54]
I am playing on the most recent version of the dw20 1.7.10 pack where the same thing happens to me as for **yenon** in #41, but I then tried to download the mod from your site on a separate minecraft instance and on there I didn't have the same issue. It all worked smoothly.

I obviously downloaded a newer version of the mod but they both got the same version number.
**OpenMods 0.6
OpenPeripheralCore 0.5.0
OpenPeripheralAddon 0.2.0
OpenPeripheralIntergration 0.1.0**

This is not a bug in the code but an error in the version number. This is very confusing because they behave differently but say they are the same versions...

**Comment by boq** [comment]
You can check exact version (snapshot number) by opening jar file as zip and viewing `META-INF/MANIFEST.MF`.

You should see something like:
```
Jenkins-Build: true
Jenkins-Tag: jenkins-OpenPeripheralAddons-105
Jenkins-ID: 2014-05-18_19-11-18
Git-Branch: master
Git-Hash: 28dc9f2
```
If you have file named `AIO-1`, then snapshot names are in file `versions.txt`.

Also, we can't control modpack contents.

**Comment by jilleJr** [comment]
Ok but then I am wondering why you are not using the version id from forge? Because on there it says they are the same. Seems silly to me that you have to extract the zip and open the file to check the version, the version should just be in the zip file name and viewable in the forge mod list *IMO*.

![Mods list](http://i.imgur.com/6zdymS5.png)

It can be very annoying to go and change the version number on the older ones but would be great if you could do it on the newer ones

**Comment by boq** [comment]
Snapshots are meant for testing only and are build automatically. We increment version number on normal releases.

Basically, if you are using snapshot, you should be aware what exactly you are  using and what are the risks. And we aren't responsible for modpack contents.

**Comment by jilleJr** [comment]
Yo @boq that's not the point I'm trying to make. **The issue is that I have 2 different versions of OpenPeripherals and they say they are the same version.** The one from the modpack was downloaded automaticly by ftb but the other one I downloaded from your site, and I didn't choose to download a snapshot. I just clicked the normal green download button on your homepage.

![OpenPeripherals downloads](http://i.imgur.com/HIp4WNW.png)

Now while comparing version numbers, I would assume that I am downloading the same version as in the modpack but apparently I am not. That is the issue I am trying to bring up here.

**Comment by boq** [comment]
The one available on openmods.info is **the only one** officially named OpenPeripheralCore 0.5.0. Every other file is snapshot. FTB does whatever it wants - so if you find renames confusing, complain to them.

Also, I'm not planning to add build number to in-game version string - that would cause problems with dependencies. But I guarantee that openmods.info won't distribute two different files with same name.

**Comment by jilleJr** [comment]
So you're saying that they changed the version number on the modpack? Thats so odd... Oh well, case closed

**Comment by boq** [comment]
Well, some modpacks do that.

Anyway, out of curiosity, I downloaded DW20 pack and compared files. They are exactly the same as ones on openmods.info. So I guess you never had most recent pack version.

**Comment by jilleJr** [comment]
Could you test if the bug is there tho? Just do a `peripheral.getType()` on a Terminal Glasses Bridge and tell me what it returns

**Comment by boq** [comment]
You are probably referring to OpenMods/OpenPeripheral-Addons#48. You probably have [this](https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.0.3) - note that this version actually contained snapshots.

**Comment by jilleJr** [comment]
Ohhh my I am not playing on the latest version (1.0.3), how silly...

I am playing on a server where they don't want to update straight away 'cause there may be bugs, and they still haven't updated. Since we waited a week or so before updating I told FTB to stop telling me there's a new update, and I'm now a few updates behind.

Wow very well then, I'll have to tell the admin to update and this will be all fine. Thank you for your support boq
