### ISSUE TITLE
Narcissistic pocket computer

### ISSUE THREAD

**Issue by jilleJr** [OpenMods/OpenPeripheral-Addons#55]
This is a suggestion for an addition to the pocket computer.

The idea of the pocket computer involves that it shouldn't be able to have peripherals except for the wireless modem. But I think it would be a cool idea if it could be *like* the narcissistic turtle, that it could see the players inventory like it if was a chest.

Since pocket computers don't support peripherals I bet it doesn't either in the API so Idk if this is possible.
Anyways would be even better if it could be wireless AND *narcissistic*, so you can tell other computers what you got on you.

**Comment by nevercast** [comment]
Will look at the API, but if it's not there it's unlikely to be added.

Dan200 is very strong on not having his mod hacked with functionality so if the API does not provide this mechanism I'm sorry to say it likely will not appear in OPA.

**Comment by Selim042** [comment]
You can add peripherals to it now, I think the functionality was added in https://github.com/austinv11/CollectiveFramework.  Something by austinv11 adds that ability, as he has his own pocket peripherals in Peripherals++.

**Comment by nevercast** [comment]
That's a dependency we wont be adding. We only use APIs provided by the mod we are writing Adapters for.

**Comment by Selim042** [comment]
K, even without using it as a dependency, it shows that it can be done.

**Comment by SinZ163** [comment]
if its not in the computercraft API, its not a thing going in OpenPeripherals.

**Comment by Selim042** [comment]
https://github.com/austinv11/PeripheralsPlusPlus/issues/77

**Comment by boq** [comment]
To end all discussions: no CC API -> no OP support.

Even if it's doable (by messing with CC internals) we are not going to spend time developing and (more importantly) maintaining such hack.

**Comment by jilleJr** [comment]
Have anyone mentioned this to dan? Maybe he could add an API for this?

Or maybe make a block that links to a players inventory like the player interface from pneumaticcraft
