### ISSUE TITLE
terminal glasses question

### ISSUE THREAD

**Issue by TOLoneWolf** [OpenMods/OpenPeripheral-Addons#56]
I have searched all over and haven't been able to find a list of the methods and the arguments for the terminal glasses.
I looked at the information on the FTB wiki but it's out of date as to how and trigger the glasses.
I was lucky enough to come across the issue on here issues#51 saying the sync() method.
Is there a place to find more update date information on how they are used?
And is there a way in computercraft to see what the parameters are that a method can except? It would be a great deal of help.
Thank you for any help you can provide.

**Comment by jilleJr** [comment]
If you wrap the terminal bridge and then do `bridge.listMethods()` you will get a nice list of methods you can use. For example:
![image](https://cloud.githubusercontent.com/assets/2477952/7637358/b2020d04-fa6d-11e4-8fd5-d8b02abbc50c.png)
It can be hard to see but some functions are next to each other on the same line, like after `addFluid` there's actually `addGradientBox` as well on the same line.

Now if you want more in depth info about the arguments you can always do `bridge.doc(method)` like so:
![image](https://cloud.githubusercontent.com/assets/2477952/7637451/495fe400-fa6e-11e4-957d-830d384efa5e.png)

And you can also use the `listMethods` and `doc` methods inside a text object, ex:
![image](https://cloud.githubusercontent.com/assets/2477952/7637504/af7c98c8-fa6e-11e4-9094-de622d1f152b.png)

**Comment by boq** [comment]
Thanks, nice explanation.

Anyway, all methods for getting documentation (including exporting to HTML file) are described in our [FAQ](http://openmods.info/faq.html).
