### ISSUE TITLE
[Bug] Terminal Glassses disconnect

### ISSUE THREAD

**Issue by TOLoneWolf** [OpenMods/OpenPeripheral-Addons#57]
While messing around with the terminal glasses I found out it disconnects the client from SSP and SMP.
It happens when you remove the glasses and you send new data like text or boxes to be displayed and then it syncs it (glasses still off). Then put them back on and the next time it tries to sync it starts to update the display and some of the information makes it on screen before the client disconnects (SMP and SSP).

Minecraft 1.7.10
Forge 10.13.2.1347-1.7.10
CodeChickenLib-1.7.10-1.1.3.127
CodeChickenCore-1.7.10-1.0.4.35
ComputerCraft1.73
NotEnoughItems-1.7.10-1.0.4.95
OpenModsLib-1.7.10-0.6

OpenPeripheral-1.7.10-AIO-1
or
OpenPeripheralAddons-1.7.10-0.2.0
OpenPeripheralCore-1.7.10-0.5.0
OpenPeripheralIntegration-1.7.10-0.1.0

results in the same disconnect.
On the server the console just shows the client disconnected with no error.

Error from MultiMC Console:
http://pastebin.com/9djffUtC

Example program:
http://pastebin.com/epeS0sxs

**Comment by boq** [comment]
#52 duplicate, already fixed.
