### ISSUE TITLE
Item selector recipe

### ISSUE THREAD

**Issue by jilleJr** [OpenMods/OpenPeripheral-Addons#61]
Simply the Item Selector peripheral recipe doesn't work. Can't craft it.

Using DW20 pack v1.3.1 which uses OpenPeripheralAddons 0.3.1

Screenshot inside NEI's recipe window
![image](https://cloud.githubusercontent.com/assets/2477952/7640108/875e54d6-fa81-11e4-9779-3cf56d641637.png)

Screenshot inside a crafting window
![image](https://cloud.githubusercontent.com/assets/2477952/7640085/6f211642-fa81-11e4-99f2-9e54c39a9a4d.png)

**Comment by boq** [comment]
It's trapped chest in middle slot.

**Comment by jilleJr** [comment]
Lol ok missed that
