### ISSUE TITLE
Making my own Terminal Glasses

### ISSUE THREAD

**Issue by Selim042** [OpenMods/OpenPeripheral-Addons#63]
Is there an API that I could use to make my own Terminal Glasses in my mod?

**Comment by boq** [comment]
[Yes](https://github.com/OpenMods/OpenPeripheral-Addons/tree/master/src/main/java/openperipheral/addons/api). And normal glasses already [use it](https://github.com/OpenMods/OpenPeripheral-Addons/blob/master/src/main/java/openperipheral/addons/glasses/ItemGlasses.java#L71).
