### ISSUE TITLE
glasses chat command doesn't work

### ISSUE THREAD

**Issue by Nathan1852** [OpenMods/OpenPeripheral-Addons#65]
I have a glasses terminal attached to a computer via the network cables. Every other event is recieved fine, I recieve the glasses_attach and glasses_detach events. But the chat command is never recieved

**Comment by boq** [comment]
Glasses chat events are triggered by `$$` (since earliest version). Though I might remove that limitation.

**Comment by Nathan1852** [comment]
I know that they are triggered by $$. It still doesn't work. The chatbox commands from MoarPeripherals work fine (with ##), but the glasses commands just don't work

**Comment by boq** [comment]
Then I'm unable to reproduce your issue. Anything interesting in logs?

**Comment by Nathan1852** [comment]
i found this: [Server thread/INFO] [MoarPeripherals/MoarPeripherals]:  [MoarP]: Detected OpenPeripheral-Addons installed. Registering the terminal glasses command as a ChatBox command so it is ignored by ChatBoxes.
I'm guessing MoarPeripherals is overwriting the command. I've already opened an Issue there and am sorry to have coused this much trouble ;)

**Comment by boq** [comment]
Hmm, I don't see how code on MoarPeripheral side can cause this...

**Comment by boq** [comment]
NOTE: just changed glasses to listen to ALL chat messages (but ones prefixed by `$$` are still not visible in chat).

**Comment by theoriginalbit** [comment]
> EDIT: Looks like it was fixed in theoriginalbit/MoarPeripherals#26, but somehow most recently released version (MoarPeripherals-1.7.10-1.7-1.53.jar) still contains old code

Yeah it seems I didn't push out a few major bug fixes a few months ago...
