### ISSUE TITLE
Terminal Glasses Server Problems

### ISSUE THREAD

**Issue by mcenderdragon** [OpenMods/OpenPeripheral-Addons#66]
At multiplayer Server the objects returnet from addBox(), addIcon ... not have the function "getId()" (I write a programm on the client, it work perfect but when i copied it into an Server computer, from ComputerCraft, it crashed ).

So I i tried to compare the objects not by ids, but by them selfs. I used the from glass_componen_mouse_down given id, at client it work, but at server if I I try to get the object with getById() the objects ar different. 
In the log are no ssues or crashes.

**Comment by boq** [comment]
OpenMods/OpenPeripheral#247 duplicate, please wait for update.

**Comment by mcenderdragon** [comment]
Ahh ok, I'll wait :)
