### ISSUE TITLE
Glasses Mouse Drag

### ISSUE THREAD

**Issue by natedogith1** [OpenMods/OpenPeripheral-Addons#72]
Currently the wireless keyboard is only missing one event available to a monitor/terminal, mouse_drag. It'd be nice if some version of this was available with the wireless keyboard as well.

**Comment by boq** [comment]
Deliberate. I don't think it's good idea: it would spam too much packets, CC events and updates.

**Comment by natedogith1** [comment]
how do terminals get away with it?

**Comment by boq** [comment]
Terminal works on character basis, we work on pixels. That's much more updates.

**Comment by TechnicianLP** [comment]
i think it would be a good approach to just send the press and release Locations (and maybe a few Points inbetween) once the mouse is released

**Comment by natedogith1** [comment]
TechnicianLP, I don't particularly like that idea, as I personally think drag is something to be used to update rendering as the user moves components around. I'd probably go with a minimum distance/time between drag events (along with probably a maximum time) if I were to implement it.

**Comment by boq** [comment]
Ok, after consideration I've added 'glasses_component_mouse_drag`. It's up to server owner to configure minimal and default differences in position and time before next event be send (via config options).
