### ISSUE TITLE
Terminal Glasses Will Not Work

### ISSUE THREAD

**Issue by FiberSprite** [OpenMods/OpenPeripheral-Addons#75]
So i am currently trying to code a simple test for my terminal glasses, but it seems to get no output at all. i cant figure out what is wrong. ive done all the coding correct just no output.

**Comment by TechnicianLP** [comment]
there a function u need to call to update the glasses-ui

**Comment by nevercast** [comment]
When one writes issues it is good practice for one to provide more information about the issue.

Firstly, your code would help.
Also have you paired the glasses?

Which version of Minecraft/Forge are you using?
Do you have Optifine?
Which version of OpenModsLib are you using?
Which version of OpenPeripheral?
Which version of OP-Addons?
Have you tried turning it off and on again?

**Comment by Selim042** [comment]
Don't forget to call `.sync()`, and can we see your code?

**Comment by boq** [comment]
Old issue and probably user error. Closing.
