### ISSUE TITLE
Terminal Glasses setAlignment

### ISSUE THREAD

**Issue by miffi1** [OpenMods/OpenPeripheral-Addons#80]
It seems like the object I use this command on does not change it's x and y value.. It stays with the x and y value specified when I created the object.

It's no a big deal, but it sucks a bit when I need the new 2DVector and not the old.

**Comment by boq** [comment]
Hmm, I don't really see a point in zeroing coordinates after alignment change. And such behaviour would be almost harmful for polygons.

**Comment by miffi1** [comment]
I don't see why we can't set the new position of the moved object. If you move it to the right why would you have the position before you moved the object?

**Comment by boq** [comment]
Ah, you meant it does not move at all after alignment? If so, then I'm sorry, but I have to response with standard 'cant-reproduce-please-provide-code'.

**Comment by miffi1** [comment]
Well it moves, but let's say I did this:

gl = peripheral.wrap("top") -- Terminal Glass Bridge
box = gl.addBox(0,0, 100, 100, 0xFFFFFF, 0)
box.setAlignment("middle", "middle")
gl.sync()

--Some reason I need the X and Y for the new POS
x = box.getX()
y = box.getY()

I get that X and Y is 0

**Comment by boq** [comment]
Oh, it works as intended. x,y values are not absolute: they define distance of object anchor (middle, top left, etc) from screen anchor. `setAlignment` just sets both of those positions at once.
