### ISSUE TITLE
Crash with snapshot

### ISSUE THREAD

**Issue by parad0xcal** [OpenMods/OpenPeripheral-Addons#82]
Not sure if this is the correct place for this as it's a snapshot issue, but I thought I'd share anyway.

Currently when I try to draw more than one icon to a surface, I'm getting a crash relating to buffer elements in openGL. This only occurs when syncing, I can create as many icons as I like, it's only after syncing that I get the full exit crash.

I know you've been doing a lot of work around these recently so thought you may want to be aware.

Obligatory crash log: http://pastebin.com/kyRr5Tws

**Comment by boq** [comment]
Fixed in 1a97a3d7538547f8d2f0fa1bd6650c5be50c75f7
