### ISSUE TITLE
Wired Network connection Dont work

### ISSUE THREAD

**Issue by Dominikzocker141** [OpenMods/OpenPeripheral-Addons#86]
Hello,
When i connect all of the blocks / peripherals in the mod with networki cables and modems i dont recive a responce,
but when i connect the peripherals directly conected to a computer it works without errors.
![2016-03-30_03 45 52](https://cloud.githubusercontent.com/assets/13309895/14129526/137de2f6-f62b-11e5-8803-9158974cce18.png)
![2016-03-30_03 46 12](https://cloud.githubusercontent.com/assets/13309895/14129527/138182bc-f62b-11e5-8eb9-5e4817612699.png)
![2016-03-30_03 46 17](https://cloud.githubusercontent.com/assets/13309895/14129528/1383e03e-f62b-11e5-8a61-51fe0ac8ff70.png)
The methods the i used:

``` lua
local p = peripheral.wrap("openperipheral_sensor_0")
local players = {}


p = peripheral.wrap("openperipheral_sensor_0")
p.getplayers


p = peripheral.find("openperipheral_sensor")
p.getplayers
```

ps. test it with all peripheral it didnt work autocomplete and all peripheral

**Comment by omglolbah** [comment]
You're using the wrong name for the function. getPlayers() is the correct name. Capital P.
There is an openp directory with a documentation program in it. "openp/docs <side/peripheral-name>" to list the functions.
You can do stuff like: 
openp/docs openperipheral_sensor_1
openp/docs openperipheral_sensor_1 getPlayers

Should list the docs for you.
