### ISSUE TITLE
All colors used with glasses are different shades of green

### ISSUE THREAD

**Issue by TheNofx68** [OpenMods/OpenPeripheral-Addons#88]
Well, I won't create a clone of this *bad* book, but here is my problem:
peripheral glass terminal seems to be working perfectly, but when doing something basic like 
p.addBox(15, 15, 15, 15, colors.blue, 1) (where p = peripheral.wrap("right"), the side of the bridge), then a p.sync(), it displays everything, but in a shade of green.

No matter the color, no matter the function..

version CraftOS 1.7

**Comment by boq** [comment]
Colors are RGB, so they are not compatible with `colors` module.

**Comment by TheNofx68** [comment]
U.U
Well, my bad, since it's not a bug :')
Thanks anyways !
