### ISSUE TITLE
Peripheral Proxy not working properly.

### ISSUE THREAD

**Issue by EmberAnimus** [OpenMods/OpenPeripheral-Addons#89]
I am using the following mods:

- Computer Craft 1.75 (From this point forward will be referenced as CC)

- Open Peripheral Core 1.3

- Open Peripheral Addons 0.5.1

The Issue:
If i connect a monitor through the proxy, with the arrow facing the monitor, the modem will outline red and "Periperhal monitor_# connected to the network" will show up. 
However, if i connect a block to the Peripheral Proxy, with the arrow facing the connected block, that is native from Minecraft, but not native to CC, the modem will not even outline in red.
Also, if i connect a block that is neither native to Minecraft nor CC (ex: MFSU from Industrial Craft 2), to the Peripheral Proxy with the arrow facing the aforementioned block, the modem that is connected to the backside of the Proxy will not be outlined in red.

**Comment by boq** [comment]
It looks like you don't have OpenPeripheralIntegration, so some of the blocks your are trying to attach (that includes MFSU and vanilla blocks) are not CC peripherals - so even if they were attached directly to computer (without modem and proxy), they wouldn't be recognized (`peripheral.isPresent` would return `false`).

**Comment by EmberAnimus** [comment]
Thank you very much, the Integration portion never managed to copy over into the mods folder for some reason. It works as intended now, closing issue thread.
