### ISSUE TITLE
How to setup workspace

### ISSUE THREAD

**Issue by hohserg1** [OpenMods/OpenPeripheral-Addons#94]
I tried:
git clone
gradlew setupDecompWorkspace
import to IDEA
gradlew genIntellejRuns(gradlew gIR)
run "Minecraft Client" and get OpenModsCore missing
add OpenModsLib jar to ./run/asset/mods and get `Duplicate Mods`

How to setup?

**Comment by boq** [comment]
You need to check out submodules:
```
git submodule init
git submodule update
```

Also, this line needs to be added to JVM arguments on run configuration:
`-Dfml.coreMods.load=openmods.core.OpenModsCorePlugin`

And then you have to make sure you also have OpenPeripheralCore in classpath -  either as deobfuscated jar in mod folder or as separate project (not sure how to do it in IDEA without messing with project structure).

**Comment by hohserg1** [comment]
Thx! It’s worth adding it to readme
